name: ItemizerX
version: ${project.version}
api-version: 1.14
description: A rewrite of Itemizer
author: _Fleek (Focusvity)
main: me.focusvity.itemizerx.ItemizerX
commands:
  itemizer:
    description: The main command for ItemizerX
    usage: /<command>
    aliases: [ii, it]
